### PR TITLE
Adding VDS support

### PR DESCRIPTION
**Pull request by ibraEssam**
You can read Camera Images using VDS.

### CODE REVIEW

**Comment by ibraEssam** [comment]
@gmnvh  any updates on this?

**Comment by gmnvh** [comment]
Sorry .. did not have the time to test it yet.

Actually I was trying to check out the changes before merging to the main
trunk but I did not find any options to do that.
What do you think would be the best way to get your changes and test before
merging ?

**Comment by ibraEssam** [comment]
cloning from my fork and installing the package will do the job. 
https://github.com/HemaZ/pycarmaker

**Comment by ibraEssam** [comment]
i've pushed a new commit to my master branch to handle multiple cameras and fix fps

**Pull request merged**
